# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
    # check these on https://fabricmc.net/develop
    minecraft_base_version=26.1.2
    minecraft_version=26.1.2
    loader_version=0.19.2
    loom_version=1.16-SNAPSHOT

# Mod Properties
    mod_version = 0.2.6
    maven_group = io.wispforest
    archives_base_name = gadget

# Dependencies
    fabric_api_version=0.149.1+26.1.2
    owo_version=0.13.0+26.1
    modmenu_version=18.0.0-beta.1
    fabric_perms_api=0.7.0
    mapping_io=0.8.0
    auoeke_result=0.4.1
    auoeke_unsafe=1.7.3
    auoeke_reflect=6.3.0
    quiltflower=1.9.0
    auth_me=9.1.0+1.21.11
    cloth_config=26.1.154
